development:
  adapter: postgresql
  database: epya_development
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost
  password: mypass

test:
  adapter: postgresql
  database: epya_test
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost
  password: mypass

production:
  adapter: postgresql
  database: epya_production
  pool: 5
  timeout: 5000
  user: dnoamqaeacfpcn
  password: 93RASI2OIrX2Ylb7XZXaBkxDLh